### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by conceptfarm** [conceptfarm/Illustrator-Line-Pie-Chart#1]
- [x] GUI for pie radius, list of values input, line thickness, checkbox link line thickness and spacer value
- [ ] Pie chart legend
- [x] Pie chart values
- [x] Pie chart colours from swatch group if possible
- [ ] Save and restore settings from existing pie charts
